second release v0.2-beta

diff --git a/assests/ssr b/assests/ssr
--- a/assests/ssr
+++ b/assests/ssr
@@ -4,35 +4,31 @@
 # simple sequence renamer #
 ###########################
 
-version=0.1
+version="0.2-beta"
 
-if [ -z $1 ]; then
+if [ $1 = "-v" ] || [ $1 = "--version" ]; then
+	echo "Simple-Sequence-Renamer: ssr-$version by hackerW1"
+	exit 0
+elif [ -z $1 ] || [ -z $2 ]; then
 	echo "[-] Syntax Error"
-	exit
+	exit 1
 fi
 
-firsts=1
-middles=10
-lasts=`expr $1 + 1`
+i=$1
+l=`expr $2 + 1`
 
-if [ $1 -lt 10 ]; then
-	while [ $firsts -lt $lasts ]
-	do
-		mv $firsts.jpg 0$firsts.jpg
-		firsts=`expr $firsts + 1`
-	done
-elif [ $1 -gt 10 ] && [ $1 -lt 100 ]; then
-	while [ $firsts -lt 10 ]
-	do
-		mv $firsts.jpg 00$firsts.jpg
-		firsts=`expr $firsts + 1`
-	done
-	while [ $middles -lt $lasts ]
-	do
-		mv $middles.jpg 0$middles.jpg
-		middles=`expr $middles + 1`
-	done
-else
-	echo "[-] ssr-$version doesn't support numbers more than 100"
-	exit
-fi
+while [ $i -lt $l ]
+do
+	if [ $i -lt 10 ]; then
+		mv $i.jpg 00$i.jpg
+		i=`expr $i + 1`
+	elif [ $i -lt 100 ]; then
+		mv $i.jpg 0$i.jpg
+		i=`expr $i + 1`
+	elif [ $i -lt 1000 ]; then
+		exit 0
+	else
+		echo "[-] Syntax Error"
+		exit 1
+	fi
+done
